// seatingData.js
export const seatingData = {
    "sections": [
      {
        "section": "one",
        "seats": [
          {"seat": "A1", "available": true},
          {"seat": "A2", "available": true},
          {"seat": "A3", "available": false},
          {"seat": "A4", "available": true},
          {"seat": "B1", "available": true},
          {"seat": "B2", "available": false},
          {"seat": "B3", "available": false},
          {"seat": "B4", "available": false},
          {"seat": "C1", "available": false},
          {"seat": "C2", "available": true},
          {"seat": "C3", "available": false},
          {"seat": "C4", "available": true},
          {"seat": "D1", "available": true},
          {"seat": "D2", "available": true},
          {"seat": "D3", "available": true},
          {"seat": "D4", "available": true}
        ]
      },
      {
        "section": "two",
        "seats": [
          {"seat": "A5", "available": true},
          {"seat": "A6", "available": true},
          {"seat": "A7", "available": true},
          {"seat": "A8", "available": true},
          {"seat": "A9", "available": true},
          {"seat": "A10", "available": false},
          {"seat": "A11", "available": false},
          {"seat": "A12", "available": false},
          {"seat": "A13", "available": false},
          {"seat": "A14", "available": true},
          {"seat": "B5", "available": true},
          {"seat": "B6", "available": true},
          {"seat": "B7", "available": true},
          {"seat": "B8", "available": true},
          {"seat": "B9", "available": true},
          {"seat": "B10", "available": true},
          {"seat": "B11", "available": true},
          {"seat": "B12", "available": true},
          {"seat": "B13", "available": true},
          {"seat": "B14", "available": true},
          {"seat": "C5", "available": true},
          {"seat": "C6", "available": true},
          {"seat": "C7", "available": true},
          {"seat": "C8", "available": true},
          {"seat": "C9", "available": true},
          {"seat": "C10", "available": true},
          {"seat": "C11", "available": true},
          {"seat": "C12", "available": true},
          {"seat": "C13", "available": true},
          {"seat": "C14", "available": true},
          {"seat": "D5", "available": true},
          {"seat": "D6", "available": true},
          {"seat": "D7", "available": true},
          {"seat": "D8", "available": true},
          {"seat": "D9", "available": true},
          {"seat": "D10", "available": true},
          {"seat": "D11", "available": true},
          {"seat": "D12", "available": true},
          {"seat": "D13", "available": true},
          {"seat": "D14", "available": true}
        ]
      },
      {
        "section": "three",
        "seats": [
          {"seat": "A15", "available": true},
          {"seat": "A16", "available": true},
          {"seat": "A17", "available": true},
          {"seat": "A18", "available": true},
          {"seat": "B15", "available": true},
          {"seat": "B16", "available": true},
          {"seat": "B17", "available": true},
          {"seat": "B18", "available": true},
          {"seat": "C15", "available": true},
          {"seat": "C16", "available": true},
          {"seat": "C17", "available": true},
          {"seat": "C18", "available": true},
          {"seat": "D15", "available": true},
          {"seat": "D16", "available": true},
          {"seat": "D17", "available": true},
          {"seat": "D18", "available": true}
        ]
      },
      {
        "section": "four",
        "seats": [
          {"seat": "E1", "available": true},
          {"seat": "E2", "available": true},
          {"seat": "E3", "available": true},
          {"seat": "E4", "available": true},
          {"seat": "F1", "available": true},
          {"seat": "F2", "available": true},
          {"seat": "F3", "available": true},
          {"seat": "F4", "available": true},
          {"seat": "G1", "available": true},
          {"seat": "G2", "available": true},
          {"seat": "G3", "available": true},
          {"seat": "G4", "available": true},
          {"seat": "H1", "available": true},
          {"seat": "H2", "available": true},
          {"seat": "H3", "available": true},
          {"seat": "H4", "available": true}
        ]
      },
      {
        "section": "five",
        "seats": [
          {"seat": "E5", "available": true},
          {"seat": "E6", "available": true},
          {"seat": "E7", "available": true},
          {"seat": "E8", "available": true},
          {"seat": "E9", "available": true},
          {"seat": "E10", "available": true},
          {"seat": "E11", "available": true},
          {"seat": "E12", "available": true},
          {"seat": "E13", "available": true},
          {"seat": "E14", "available": true},
          {"seat": "F5", "available": true},
          {"seat": "F6", "available": true},
          {"seat": "F7", "available": true},
          {"seat": "F8", "available": true},
          {"seat": "F9", "available": true},
          {"seat": "F10", "available": true},
          {"seat": "F11", "available": true},
          {"seat": "F12", "available": true},
          {"seat": "F13", "available": true},
          {"seat": "F14", "available": true},
          {"seat": "G5", "available": true},
          {"seat": "G6", "available": true},
          {"seat": "G7", "available": true},
          {"seat": "G8", "available": true},
          {"seat": "G9", "available": true},
          {"seat": "G10", "available": true},
          {"seat": "G11", "available": true},
          {"seat": "G12", "available": true},
          {"seat": "G13", "available": true},
          {"seat": "G14", "available": true},
          {"seat": "H5", "available": true},
          {"seat": "H6", "available": true},
          {"seat": "H7", "available": true},
          {"seat": "H8", "available": true},
          {"seat": "H9", "available": true},
          {"seat": "H10", "available": true},
          {"seat": "H11", "available": true},
          {"seat": "H12", "available": true},
          {"seat": "H13", "available": true},
          {"seat": "H14", "available": true}
        ]
      },
      {
        "section": "six",
        "seats": [
          {"seat": "E15", "available": true},
          {"seat": "E16", "available": true},
          {"seat": "E17", "available": true},
          {"seat": "E18", "available": true},
          {"seat": "F15", "available": true},
          {"seat": "F16", "available": true},
          {"seat": "F17", "available": true},
          {"seat": "F18", "available": true},
          {"seat": "G15", "available": true},
          {"seat": "G16", "available": true},
          {"seat": "G17", "available": true},
          {"seat": "G18", "available": true},
          {"seat": "H15", "available": true},
          {"seat": "H16", "available": true},
          {"seat": "H17", "available": true},
          {"seat": "H18", "available": true}
        ]
      },
      {
        "section": "seven",
        "seats": [
          {"seat": "I1", "available": true},
          {"seat": "I2", "available": true},
          {"seat": "I3", "available": true},
          {"seat": "I4", "available": true},
          {"seat": "J1", "available": true},
          {"seat": "J2", "available": true},
          {"seat": "J3", "available": true},
          {"seat": "J4", "available": true},
          {"seat": "K1", "available": true},
          {"seat": "K2", "available": true},
          {"seat": "K3", "available": true},
          {"seat": "K4", "available": true},
          {"seat": "L1", "available": true},
          {"seat": "L2", "available": true},
          {"seat": "L3", "available": true},
          {"seat": "L4", "available": true}
        ]
      },
      {
        "section": "eight",
        "seats": [
          {"seat": "I5", "available": true},
          {"seat": "I6", "available": true},
          {"seat": "I7", "available": true},
          {"seat": "I8", "available": true},
          {"seat": "I9", "available": true},
          {"seat": "I10", "available": true},
          {"seat": "I11", "available": true},
          {"seat": "I12", "available": true},
          {"seat": "I13", "available": true},
          {"seat": "I14", "available": true},
          {"seat": "J5", "available": true},
          {"seat": "J6", "available": true},
          {"seat": "J7", "available": true},
          {"seat": "J8", "available": true},
          {"seat": "J9", "available": true},
          {"seat": "J10", "available": true},
          {"seat": "J11", "available": true},
          {"seat": "J12", "available": true},
          {"seat": "J13", "available": true},
          {"seat": "J14", "available": true},
          {"seat": "K5", "available": true},
          {"seat": "K6", "available": true},
          {"seat": "K7", "available": true},
          {"seat": "K8", "available": true},
          {"seat": "K9", "available": true},
          {"seat": "K10", "available": true},
          {"seat": "K11", "available": true},
          {"seat": "K12", "available": true},
          {"seat": "K13", "available": true},
          {"seat": "K14", "available": true},
          {"seat": "L5", "available": true},
          {"seat": "L6", "available": true},
          {"seat": "L7", "available": true},
          {"seat": "L8", "available": true},
          {"seat": "L9", "available": true},
          {"seat": "L10", "available": true},
          {"seat": "L11", "available": true},
          {"seat": "L12", "available": true},
          {"seat": "L13", "available": true},
          {"seat": "L14", "available": true}
        ]
      },
      {
        "section": "nine",
        "seats": [
          {"seat": "I15", "available": true},
          {"seat": "I16", "available": true},
          {"seat": "I17", "available": true},
          {"seat": "I18", "available": true},
          {"seat": "J15", "available": true},
          {"seat": "J16", "available": true},
          {"seat": "J17", "available": true},
          {"seat": "J18", "available": true},
          {"seat": "K15", "available": true},
          {"seat": "K16", "available": true},
          {"seat": "K17", "available": true},
          {"seat": "K18", "available": true},
          {"seat": "L15", "available": true},
          {"seat": "L16", "available": true},
          {"seat": "L17", "available": true},
          {"seat": "L18", "available": true}
        ]
      }
    ]
  }
  